-- MySQL Script generated by MySQL Workbench
-- Tue Aug 11 23:01:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema weightpredictionappdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema weightpredictionappdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `weightpredictionappdb` DEFAULT CHARACTER SET utf8 ;
USE `weightpredictionappdb` ;

-- -----------------------------------------------------
-- Table `weightpredictionappdb`.`users_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weightpredictionappdb`.`users_table`;
CREATE TABLE IF NOT EXISTS `weightpredictionappdb`.`users_table` (
  `user_id` SMALLINT(3) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(16) NOT NULL COMMENT 'First, last, user, nickname.... Doesn\'t matter. Just enter a string to act as an identifier',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weightpredictionappdb`.`dateweight_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weightpredictionappdb`.`dateweight_table`;
CREATE TABLE IF NOT EXISTS `weightpredictionappdb`.`dateweight_table` (
  `user_id` SMALLINT(3) NOT NULL,
  `date` DATE NOT NULL,
  `weight` DECIMAL(4,1) NULL,
  `origin` SET('user', 'algo') NULL,
  PRIMARY KEY (`date`, `user_id`),
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `pkfk_dw_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `weightpredictionappdb`.`users_table` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `weightpredictionappdb`.`predictions_table`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `weightpredictionappdb`.`predictions_table`;
CREATE TABLE IF NOT EXISTS `weightpredictionappdb`.`predictions_table` (
  `user_id` SMALLINT(3) NOT NULL,
  `date` DATE NOT NULL,
  `method` SET('autoarima', 'naivedrift') NOT NULL,
  `value` DECIMAL(4,1) NULL,
  PRIMARY KEY (`user_id`, `date`, `method`),
  INDEX `pkfk_date_idx` (`date` ASC) VISIBLE,
  CONSTRAINT `pkfk_pred_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `weightpredictionappdb`.`users_table` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `pkfk_date`
    FOREIGN KEY (`date`)
    REFERENCES `weightpredictionappdb`.`dateweight_table` (`date`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
