-- MySQL Script generated by MySQL Workbench
-- Thu Jul 23 14:38:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema date_weight_pairs
-- -----------------------------------------------------
-- Simple database. That's all there is.

-- -----------------------------------------------------
-- Schema date_weight_pairs
--
-- Simple database. That's all there is.
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `date_weight_pairs` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `date_weight_pairs` ;

-- -----------------------------------------------------
-- Table `date_weight_pairs`.`dateWeightTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `date_weight_pairs`.`dateWeightTable` (
  `date` DATE NOT NULL,
  `weight` DECIMAL NULL,
  PRIMARY KEY (`date`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
